export const DEFAULT_USER = {
  name: "Dianne Russell",
  email: "dainne.ressell@gmail.com",
  phone: "(671) 555-0110",
  role: "customer",
  avatar: "/dianne-avatar.jpg",
  billingAddress: {
    firstName: "Dianne",
    lastName: "Russell",
    company: "Zakirsoft",
    street: "4140 Parker Rd. Allentown, New Mexico 31134",
    country: "United States",
    state: "Washington DC",
    zipCode: "20033",
    email: "dainne.ressell@gmail.com",
    phone: "(603) 555-0123",
  },
};

export const MOCK_ORDERS = [
  {
    id: "3933",
    displayId: "#3933",
    date: "4 April, 2021",
    total: 135.0,
    productCount: 5,
    status: "Processing",
    paymentMethod: "Paypal",
    subtotal: 150.0,
    discount: "10%",
    shipping: "Free",
    step: 2,
    items: [
      { name: "Red Capsicum", price: 14.0, quantity: 5, image: "/RedCapsicum.jpg" },
      { name: "Green Capsicum", price: 14.0, quantity: 2, image: "/GreenCapsicum.png" },
      { name: "Green Chili", price: 26.7, quantity: 1, image: "/GreenChilli.png" },
    ],
  },
  {
    id: "5045",
    displayId: "#5045",
    date: "27 Mar, 2021",
    total: 25.0,
    productCount: 1,
    status: "on the way",
    paymentMethod: "Credit Card",
    subtotal: 25.0,
    discount: "0%",
    shipping: "Free",
    step: 3,
    items: [
      { name: "Fresh Cauliflower", price: 25.0, quantity: 1, image: "/FreshCauliflower.png" },
    ],
  },
  {
    id: "5028",
    displayId: "#5028",
    date: "20 Mar, 2021",
    total: 250.0,
    productCount: 4,
    status: "Completed",
    paymentMethod: "Paypal",
    subtotal: 270.0,
    discount: "7%",
    shipping: "Free",
    step: 4,
    items: [
      { name: "Green Capsicum", price: 14.0, quantity: 5, image: "/GreenCapsicum.png" },
      { name: "Red Tomato", price: 12.0, quantity: 15, image: "/Red Tomato.png" },
    ],
  },
  {
    id: "4600",
    displayId: "#4600",
    date: "19 Mar, 2021",
    total: 35.0,
    productCount: 1,
    status: "Completed",
    paymentMethod: "COD",
    subtotal: 35.0,
    discount: "0%",
    shipping: "Free",
    step: 4,
    items: [
      { name: "Surjapur Mango", price: 35.0, quantity: 1, image: "/Surjapur Mango.png" },
    ],
  },
  {
    id: "4152",
    displayId: "#4152",
    date: "April 24, 2021",
    total: 84.0,
    productCount: 3,
    status: "Processing",
    paymentMethod: "Paypal",
    subtotal: 365.0,
    discount: "20%",
    shipping: "Free",
    step: 2,
    items: [
      { name: "Red Capsicum", price: 14.0, quantity: 5, image: "/RedCapsicum.jpg" },
      { name: "Green Capsicum", price: 14.0, quantity: 2, image: "/GreenCapsicum.png" },
      { name: "Green Chili", price: 26.7, quantity: 10, image: "/GreenChilli.png" },
    ],
  },
  {
    id: "8811",
    displayId: "#8811",
    date: "10 Mar, 2021",
    total: 345.0,
    productCount: 7,
    status: "Completed",
    paymentMethod: "Credit Card",
    subtotal: 360.0,
    discount: "4%",
    shipping: "Free",
    step: 4,
    items: [
      { name: "Red Capsicum", price: 14.0, quantity: 7, image: "/RedCapsicum.jpg" },
      { name: "Green Capsicum", price: 14.0, quantity: 5, image: "/GreenCapsicum.png" },
    ],
  },
  {
    id: "3536",
    displayId: "#3536",
    date: "5 Mar, 2021",
    total: 560.0,
    productCount: 2,
    status: "Completed",
    paymentMethod: "Paypal",
    subtotal: 580.0,
    discount: "3%",
    shipping: "Free",
    step: 4,
    items: [
      { name: "Low-Fat Meat", price: 280.0, quantity: 2, image: "/Low-FatMeat.png" },
    ],
  },
  {
    id: "1374",
    displayId: "#1374",
    date: "27 Feb, 2021",
    total: 560.0,
    productCount: 2,
    status: "Completed",
    paymentMethod: "Paypal",
    subtotal: 560.0,
    discount: "0%",
    shipping: "Free",
    step: 4,
    items: [
      { name: "Low-Fat Meat", price: 280.0, quantity: 2, image: "/Low-FatMeat.png" },
    ],
  },
  {
    id: "7791",
    displayId: "#7791",
    date: "25 Feb, 2021",
    total: 560.0,
    productCount: 2,
    status: "Completed",
    paymentMethod: "Credit Card",
    subtotal: 560.0,
    discount: "0%",
    shipping: "Free",
    step: 4,
    items: [
      { name: "Low-Fat Meat", price: 280.0, quantity: 2, image: "/Low-FatMeat.png" },
    ],
  },
  {
    id: "4848",
    displayId: "#4848",
    date: "24 Feb, 2021",
    total: 23.0,
    productCount: 1,
    status: "Completed",
    paymentMethod: "COD",
    subtotal: 23.0,
    discount: "0%",
    shipping: "Free",
    step: 4,
    items: [
      { name: "Green Lettuce", price: 23.0, quantity: 1, image: "/GreenLettuce.png" },
    ],
  },
  {
    id: "5948",
    displayId: "#5948",
    date: "20 Feb, 2021",
    total: 23.0,
    productCount: 1,
    status: "Completed",
    paymentMethod: "Paypal",
    subtotal: 23.0,
    discount: "0%",
    shipping: "Free",
    step: 4,
    items: [
      { name: "Chinese Cabbage", price: 23.0, quantity: 1, image: "/ChineseCabbage.png" },
    ],
  },
  {
    id: "1577",
    displayId: "#1577",
    date: "12 Oct, 2020",
    total: 23.0,
    productCount: 1,
    status: "Completed",
    paymentMethod: "Paypal",
    subtotal: 23.0,
    discount: "0%",
    shipping: "Free",
    step: 4,
    items: [
      { name: "Green Apple", price: 23.0, quantity: 1, image: "/greenApple.png" },
    ],
  },
];

export const RECENT_DASHBOARD_ORDERS = [
  {
    id: "738",
    displayId: "#738",
    date: "8 Sep, 2020",
    total: 135.0,
    productCount: 5,
    status: "Processing",
    paymentMethod: "Paypal",
    subtotal: 150.0,
    discount: "10%",
    shipping: "Free",
    step: 2,
    items: [
      { name: "Red Capsicum", price: 14.0, quantity: 5, image: "/RedCapsicum.jpg" },
      { name: "Green Capsicum", price: 14.0, quantity: 2, image: "/GreenCapsicum.png" },
    ],
  },
  {
    id: "703",
    displayId: "#703",
    date: "24 May, 2020",
    total: 25.0,
    productCount: 1,
    status: "on the way",
    paymentMethod: "Credit Card",
    subtotal: 25.0,
    discount: "0%",
    shipping: "Free",
    step: 3,
    items: [
      { name: "Fresh Cauliflower", price: 25.0, quantity: 1, image: "/FreshCauliflower.png" },
    ],
  },
  {
    id: "130",
    displayId: "#130",
    date: "22 Oct, 2020",
    total: 250.0,
    productCount: 4,
    status: "Completed",
    paymentMethod: "Paypal",
    subtotal: 270.0,
    discount: "7%",
    shipping: "Free",
    step: 4,
    items: [
      { name: "Green Capsicum", price: 14.0, quantity: 4, image: "/GreenCapsicum.png" },
    ],
  },
  {
    id: "561",
    displayId: "#561",
    date: "1 Feb, 2020",
    total: 35.0,
    productCount: 1,
    status: "Completed",
    paymentMethod: "COD",
    subtotal: 35.0,
    discount: "0%",
    shipping: "Free",
    step: 4,
    items: [
      { name: "Surjapur Mango", price: 35.0, quantity: 1, image: "/Surjapur Mango.png" },
    ],
  },
  {
    id: "536",
    displayId: "#536",
    date: "21 Sep, 2020",
    total: 578.0,
    productCount: 13,
    status: "Completed",
    paymentMethod: "Paypal",
    subtotal: 620.0,
    discount: "6%",
    shipping: "Free",
    step: 4,
    items: [
      { name: "Low-Fat Meat", price: 280.0, quantity: 2, image: "/Low-FatMeat.png" },
      { name: "Red Capsicum", price: 14.0, quantity: 5, image: "/RedCapsicum.jpg" },
    ],
  },
  {
    id: "492",
    displayId: "#492",
    date: "22 Oct, 2020",
    total: 345.0,
    productCount: 7,
    status: "Completed",
    paymentMethod: "Paypal",
    subtotal: 360.0,
    discount: "4%",
    shipping: "Free",
    step: 4,
    items: [
      { name: "Red Capsicum", price: 14.0, quantity: 5, image: "/RedCapsicum.jpg" },
      { name: "Green Chili", price: 26.7, quantity: 2, image: "/GreenChilli.png" },
    ],
  },
];

export const getOrderById = (orderId) => {
  const cleanId = String(orderId).replace("#", "");
  const found =
    MOCK_ORDERS.find((o) => o.id === cleanId || o.displayId === `#${cleanId}`) ||
    RECENT_DASHBOARD_ORDERS.find((o) => o.id === cleanId || o.displayId === `#${cleanId}`);

  if (found) return found;

  // Default fallback matching Image 3 if not specifically found
  return {
    id: cleanId || "4152",
    displayId: `#${cleanId || "4152"}`,
    date: "April 24, 2021",
    total: 84.0,
    productCount: 3,
    status: "Processing",
    paymentMethod: "Paypal",
    subtotal: 365.0,
    discount: "20%",
    shipping: "Free",
    step: 2,
    items: [
      { name: "Red Capsicum", price: 14.0, quantity: 5, image: "/RedCapsicum.jpg" },
      { name: "Green Capsicum", price: 14.0, quantity: 2, image: "/GreenCapsicum.png" },
      { name: "Green Chili", price: 26.7, quantity: 10, image: "/GreenChilli.png" },
    ],
  };
};
